import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { getData } from '../store/reduccers/AllReducers'

export default function Home() {
  // const [user, setUser] = useState([])
  const dispatch = useDispatch()
  
  useEffect(() => {
     try {
      fetch('https://randomuser.me/api/')
      .then(res => res.json())
      .then(res => {
        console.log(res.results)
        dispatch(getData(res.results))
      })
     } catch (error) {
       console.log(error)
     }
  },[])

  const showName = useSelector((state) => state.allData.users[0])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{showName ? showName.name.first : 'Loading' }</h1>
      </main>
    </div>
  )
}
